### ISSUE TITLE
Carousel show the second image of list instead of first

### ISSUE THREAD

**Issue by gabofer82** [marjandn/fan_carousel_image_slider#2]
Hi!

I want to share this curious behavior.

The initialPageIndex attribute, which defaults to 1, should display the first image in the image list (I guess), however it displays the second image.
I have changed initialPageIndex to 0 but the execution throws an assertion error on line 49:
`` assert(initalPageIndex` < (imagesLink.length - 1) && initalPageIndex > 0);`

Which may be?

Thankyou for your time.

**Comment by marjandn** [comment]
Hello,
For initailPageIndex, it's based on the List index so if you want to show the first item in your list you should define 0 for the initialPageIndex field.

But about the issue, How many items are there in your list of images?

**Comment by manuduxi** [comment]
Hello @marjandn ,
I just faced the same issue when the length of images is < 3

```dart
assert(initalPageIndex < (imagesLink.length - 1) && initalPageIndex > 0);
```

so by default the initalPageIndex is one, which means that if the imagesLink length is smaller or equal two the assert will fail

```dart
assert(1 < (2 - 1));
```

a fix might be 

```dart
assert(initalPageIndex <= (imagesLink.length - 1) && initalPageIndex >= 0);
```

**Comment by marjandn** [comment]
You are right, I fix this issue and updated the package on pub.dev.

Thanks for reporting this issue.
@gabofer82 @manuduxi

**Comment by gabofer82** [comment]
Thankyou @marjandn for your work!
